### ISSUE TITLE
蔓二段ジャンプグリッチ

### ISSUE THREAD

**Issue by poly65536** [Vau1ters/air-po#150]
蔓にジャンプできる判定がある

**Comment by Sobaya007** [comment]
- 壁よりもツタのほうがめり込んでしまう量が多く、そのせいで足の当たり判定にツタが衝突・着地判定が発動して二段ジャンプが起きる
- なんでめり込み量に差異が出るかは不明
- ためしにwallのheightを増やすとツタと同じように二段ジャンプできるようになった

**Comment by Sobaya007** [comment]
# 結論
もともとAABBの高さが一定以上の物体に対しては二段ジャンプできる仕様になってしまっていた。
理由↓
現状Playerのbodyの当たり判定とfootの当たり判定の幅の差が2なので片側で1だけfootが短い。
一方Playerのx方向の最大速度は100で、1フレームあたりの秒数delta = 1/60が掛かるので、1フレームでPlayerはx方向に最大1.6移動できる。
よってx方向に最大速度で移動していると壁に横からfootがあたってlanding = trueになる。
ところがどっこい、playerのfootのclipToleranceYが14になっているので、十分小さい物体に対してはclipToleranceX = 3が効いてちょっと細身の当たり判定になる。
だから「十分小さい物体に」「横から」「footが」当たり判定をする場合には衝突しづらくなり、壁では二段ジャンプできなくなっていた。

証明完了 Q.E.D.
