### ISSUE TITLE
タイトルからゲーム画面に遷移するときに少し固まる

### ISSUE THREAD

**Issue by poly65536** [Vau1ters/air-po#166]
ロード画面はさみたい

**Comment by Sobaya007** [comment]
WebWorkerで重い処理を逃がそうとしたが、WebWorker ThreadでPIXIの処理が動かない(より正確にはWebWorkerのrootファイルからのdependency graphにpixiが含まれていた場合に死ぬ)のでマルチスレッド化は厳しい

**Comment by wake-wakame** [comment]
マップ生成時の処理が一部meta buildに移ったことで軽くなったのでよし
