### ISSUE TITLE
壁の画像

### ISSUE THREAD

**Issue by poly65536** [Vau1ters/air-po#211]
外気に触れてる面が3つ以上の壁画像が用意されてない
![image](https://user-images.githubusercontent.com/29621879/107870083-e9d56600-6ed8-11eb-8ad6-892facb70b4e.png)

外気に触れてない壁もない
![image](https://user-images.githubusercontent.com/29621879/107954885-64d57400-6fe0-11eb-80e0-b98069d3d748.png)

**Comment by Sobaya007** [comment]
https://hackmd.io/JjPEdU1jSZiGQZRIOzhq1w
