### ISSUE TITLE
背景の座標計算をカメラ依存にする

### ISSUE THREAD

**Issue by poly65536** [Vau1ters/air-po#388]
カメラが動いていないのに背景が動くと違和感があるため、背景の座標計算をプレイヤーの位置でなくカメラ座標依存に直す
![Animation1](https://user-images.githubusercontent.com/29621879/141668081-36fcecc6-4cf6-46ac-a7af-ccd7db9b990c.gif)

**Comment by wake-wakame** [comment]
なんか大丈夫です
